### PR TITLE
Add Image loader API along with misc changes

### PR DESCRIPTION
**Pull request by mikiSpoko200**
Listing of all possible classification targets. Loader API will need this parameter as configuration.

### CODE REVIEW

**Comment by mikiSpoko200** [comment]
Initial commit with changes to utils was erroneous (I love having no static typing) - the first commit fixes the issue.
Second commit contains initial implementation with partial documentation of batching file loader.

**Review by tymeg — COMMENTED** [review]
Looks very elegant! I've got two small notes/questions:
1) typos in lines 71-72: should be 'grouped' instead of 'groupped'
2) do the 2 methods in BatchLoader need to be static? Will we sometimes use them without objects or something?

**Comment by mikiSpoko200** [comment]
> Looks very elegant! I've got two small notes/questions:
> 
> 1. typos in lines 71-72: should be 'grouped' instead of 'groupped'
> 2. do the 2 methods in BatchLoader need to be static? Will we sometimes use them without objects or something?

Ah typo right, thanks. As to these two static methods these are completely private and indeed static. They create the `BatchLoader._index` which is a static member that is initialized when first BatchLoader instance is created, but again all the fields prefixed with underscore (except magic / dunder methods of course) are [private](https://peps.python.org/pep-0008/#descriptive-naming-styles).

**Comment by tymeg** [comment]
OK right so it's the base class Iterable requirement as I understand. We'll fix the typo later by the way, I approve the pull request!

**Review by tymeg — APPROVED** [review]
Good work here

**Pull request merged**
